tls:
  enabled: true
  authClient: true
  existingSecret: "valkey-tls-secret"
  certFilename: "tls.crt"
  certKeyFilename: "tls.key"
  certCAFilename: "ca.crt"

replica:
  replicaCount: 0

auth:
  enabled: false

resources:
  requests:
    cpu: 1
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1024Mi
