version: 0.0
os: linux
files:
  - source: ./nodecosmos
    destination: /usr/local/bin/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: scripts/cleanup_previous.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 60
      runas: root
