[workspace]
resolver = "2"
members = [
    "nodecosmos",
    "charybdis-cmd/migrate",
    "charybdis-cmd/modelize",
    "charybdis",
    "charybdis-macros",
    "charybdis-parser",
]
[profile.release]
opt-level = 3
lto = true
