eck-elasticsearch:
  nodeSets:
    - name: masters
      replicaCount: 0
      count: 1
      config:
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                limits:
                  memory: 1Gi
                  cpu: 1
          transport:
            tls:
              certificate:
                secretName: elastic-tls-secret
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
              storageClassName: standard
