# Scylla Manager image
image:
  tag: 3.4.0@sha256:6424c36929b39ef4e679ee7d61578b1070e28c186b23b278147fde8e391d9db1

# Resources allocated to Scylla Manager Controller pods
controllerResources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 32Mi
# Scylla instance for Manager
scylla:
  developerMode: true
  scyllaImage:
    tag: 6.2.0
  agentImage:
    tag: 3.4.0@sha256:441403aed8880cad1feef68aa7a8ee9ffd99a458dc1dcff3dc54ce5bf3cb07b7
  datacenter: manager-dc
  racks:
    - name: manager-rack
      members: 1
      storage:
        capacity: 5Gi
        storageClassName: scylladb-local-xfs
      resources:
        limits:
          cpu: 1
          memory: 2Gi
        requests:
          cpu: 1
          memory: 2Gi
      placement:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: scylla.scylladb.com/node-type
                    operator: In
                    values:
                      - scylla
        tolerations:
          - effect: NoSchedule
            key: scylla-operator.scylladb.com/dedicated
            operator: Equal
            value: scyllaclusters
