[package]
name = "charybdis_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.64"
syn = { version = "2.0.10", features = ["full"] }
quote = "1.0.26"
serde = { version = "1.0.189", features = ["derive"] }
scylla = "0.10.0"
serde_json = "1.0.107"
colored = { version = "2.0.0", features = [] }
walkdir = "2.3.3"
