apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-pv-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  local:
    path: /mnt/data/elasticsearch-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: elastic/node-type
              operator: In
              values:
                - elastic
