---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylladb-local-pv-manager
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: scylladb-local-xfs
  local:
    path: /mnt/data-scylla-manager
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: scylla.scylladb.com/node-type
              operator: In
              values:
                - scylla
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylladb-local-pv-0
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: scylladb-local-xfs
  local:
    path: /mnt/data-scylla-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: scylla.scylladb.com/node-type
              operator: In
              values:
                - scylla
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: scylladb-local-pv-1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: scylladb-local-xfs
  local:
    path: /mnt/data-scylla-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: scylla.scylladb.com/node-type
              operator: In
              values:
                - scylla
