use charybdis::prelude::*;

#[charybdis_udt_model(type_name = "address")]
pub struct Address {
    pub street: Text,
    pub city: Text,
    pub state: Text,
    pub zip: Text,
    pub country: Text,
    pub country_2: Text,
    pub country_3: Text,
    pub country_4: Text,
    pub country_5: Text,
    pub country_6: Text,
    pub country_7: Text,
    pub country_8: Text,
    pub country_9: Text,
    pub country_10: Text,
    pub country_11: Text,
    pub country_12: Text,
    pub country_13: Text,
    pub country_14: Text,
    pub country_15: Text,
    pub country_16: Text,
    pub country_17: Text,
    pub country_18: Text,
    pub country_19: Text,
    pub country_20: Text,
    pub country_21: Text,
    pub country_22: Text,
    pub country_23: Text,
    pub country_24: Text,
    pub country_25: Text,
    pub country_26: Text,
    pub country_27: Text,
    pub country_28: Text,
    pub country_29: Text,
    pub country_30: Text,
}
