[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"  # Use the latest version
uuid = { version = "1", features = ["v4"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "vec_set"
harness = false