name: Build and Deploy Rust Application to EC2
on:
  push:
    branches:
      - main
env:
  BUCKET_NAME: aws-nodecosmos-bucket
  AWS_REGION: us-east-1
  CARGO_TERM_COLOR: always
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    container:
      image: nodecosmos/aarch64_env:latest
    env:
      PATH: /root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      RUSTUP_HOME: /root/.rustup
      CARGO_HOME: /root/.cargo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::714215625955:role/github-actions
          role-session-name: s3session
          aws-region: ${{ env.AWS_REGION }}
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache OpenSSL and Toolchain
        uses: actions/cache@v4
        with:
          path: |
            /usr/local/openssl-aarch64
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: ${{ runner.os }}-openssl-and-toolchain
      - name: Build for aarch64
        run: |
          export OPENSSL_DIR=/usr/local/openssl-aarch64
          export OPENSSL_LIB_DIR=/usr/local/openssl-aarch64/lib
          export OPENSSL_INCLUDE_DIR=/usr/local/openssl-aarch64/include
          cargo build --release --target aarch64-unknown-linux-gnu --verbose
          unset OPENSSL_DIR
          unset OPENSSL_LIB_DIR
          unset OPENSSL_INCLUDE_DIR
      - name: Decode SSL Certificate
        run: echo "${{ secrets.SCYLLA_CLIENT_CERT }}" | base64 --decode > client.crt

      - name: Decode SSL Key
        run: echo "${{ secrets.SCYLLA_CLIENT_KEY }}" | base64 --decode > client.key

      - name: Decode CA Certificate
        run: echo "${{ secrets.CA_CERT }}" | base64 --decode > ca.crt

      #      - name: Run migrations
      #        run: |
      #          migrate --keyspace nodecosmos --host ${{ secrets.SCYLLA_URL }} --drop-and-replace --ca ca.crt --cert client.crt --key client.key

      - name: Zip the binary appspec.yml and scripts
        run: |
          zip -j nodecosmos.zip target/aarch64-unknown-linux-gnu/release/nodecosmos
          zip -r nodecosmos.zip appspec.yml scripts
      - name: Upload to S3
        run: |
          aws s3 cp nodecosmos.zip s3://$BUCKET_NAME/nodecosmos.zip
      - name: Deploy to EC2
        run: |
          deployment_output=$(aws deploy create-deployment \
          --application-name Nodecosmos \
          --s3-location bucket=$BUCKET_NAME,key=nodecosmos.zip,bundleType=zip \
          --deployment-group-name nodecosmos-deployment-group \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --description "Deploying nodecosmos" \
          --query 'deploymentId' \
          --output text)
          echo "deployment_id=$deployment_output" >> $GITHUB_OUTPUT
