name: Build and Deploy Rust Application to EC2

on:
  push:
    branches:
      - main

env:
  BUCKET_NAME: aws-nodecosmos-bucket
  AWS_REGION: us-east-1
  CARGO_TERM_COLOR: always
  OPENSSL_VERSION: openssl-1.1.1l
  OPENSSL_INSTALL_DIR: /usr/local/openssl-aarch64
  ENV: production

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::714215625955:role/github-actions
          role-session-name: s3session
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Toolchain
        env:
          toolchain: stable
          targets: aarch64-unknown-linux-gnu
        shell: bash
        run: |
          if [[ -z "$toolchain" && ( -f "rust-toolchain" || -f "rust-toolchain.toml" ) ]]
          then
            rustup show
            if [[ -n $components ]]; then
              rustup component add ${components//,/ }
            fi
            if [[ -n $targets ]]; then
              rustup target add ${targets//,/ }
            fi
          else
            if [[ -z "$toolchain" ]]
            then
              toolchain=stable
            fi
            rustup toolchain install stable --profile minimal --no-self-update
            rustup default stable
            rustup target add aarch64-unknown-linux-gnu
            sudo apt-get update
            sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          fi
      - name: Cache OpenSSL
        uses: actions/cache@v2
        with:
          path: ${{ env.OPENSSL_INSTALL_DIR }}
          key: ${{ runner.os }}-${{ env.OPENSSL_VERSION }}-${{ hashFiles('**/openssl.md5') }}

      - name: Download and compile OpenSSL
        if: steps.cache-openssl.outputs.cache-hit != 'true'
        run: |
          wget https://www.openssl.org/source/${{ env.OPENSSL_VERSION }}.tar.gz
          tar -xzf ${{ env.OPENSSL_VERSION }}.tar.gz
          cd ${{ env.OPENSSL_VERSION }}
          ./Configure linux-aarch64 no-shared --prefix=${{ env.OPENSSL_INSTALL_DIR }} --cross-compile-prefix=aarch64-linux-gnu-
          make
          sudo make install
        env:
          OPENSSL_DIR: ${{ env.OPENSSL_INSTALL_DIR }}
          OPENSSL_LIB_DIR: ${{ env.OPENSSL_INSTALL_DIR }}/lib
          OPENSSL_INCLUDE_DIR: ${{ env.OPENSSL_INSTALL_DIR }}/include

      - name: Set environment for OpenSSL
        run: |
          echo "OPENSSL_DIR=${{ env.OPENSSL_INSTALL_DIR }}" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=${{ env.OPENSSL_INSTALL_DIR }}/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=${{ env.OPENSSL_INSTALL_DIR }}/include" >> $GITHUB_ENV
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/aarch64-unknown-linux-gnu
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build for aarch64
        run: cargo build --release --target aarch64-unknown-linux-gnu --verbose
      - name: Zip the binary appspec.yml and scripts
        run: |
          zip -j nodecosmos.zip target/aarch64-unknown-linux-gnu/release/nodecosmos
          zip -r nodecosmos.zip appspec.yml scripts
      - name: Upload to S3
        run: |
          aws s3 cp nodecosmos.zip s3://$BUCKET_NAME/nodecosmos.zip
      - name: Deploy to EC2
        run: |
          aws deploy create-deployment \
            --application-name Nodecosmos \
            --s3-location bucket=$BUCKET_NAME,key=nodecosmos.zip,bundleType=zip \
            --deployment-group-name nodecosmos-deployment-group \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --description "Deploying nodecosmos"
